//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClient.MyServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyServiceReference.IMyServiceContract")]
    public interface IMyServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyServiceContract/Say", ReplyAction="http://tempuri.org/IMyServiceContract/SayResponse")]
        byte[] Say(byte[] bytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyServiceContract/Say", ReplyAction="http://tempuri.org/IMyServiceContract/SayResponse")]
        System.Threading.Tasks.Task<byte[]> SayAsync(byte[] bytes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyServiceContractChannel : MyClient.MyServiceReference.IMyServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceContractClient : System.ServiceModel.ClientBase<MyClient.MyServiceReference.IMyServiceContract>, MyClient.MyServiceReference.IMyServiceContract {
        
        public MyServiceContractClient() {
        }
        
        public MyServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] Say(byte[] bytes) {
            return base.Channel.Say(bytes);
        }
        
        public System.Threading.Tasks.Task<byte[]> SayAsync(byte[] bytes) {
            return base.Channel.SayAsync(bytes);
        }
    }
}
